import {
    UserGroupIcon,
    WrenchScrewdriverIcon,
    WindowIcon,
    PuzzlePieceIcon,
    CubeIcon,
    SquaresPlusIcon,
    Cog6ToothIcon,
    SwatchIcon,
} from "@heroicons/react/24/solid";

export default [
    {
        id: "tellers",
        name: "Tellers",
        icon: <WindowIcon className="h-4" />,
        route: "admin.tellers.index",
        permission: "DASHBOARD_TELLER",
    },
    {
        id: "qu",
        name: "Qu",
        icon: <PuzzlePieceIcon className="h-4" />,
        route: "admin.qu.index",
        permission: "REGISTRATION",
    },
    // {
    //     id: "priority",
    //     name: "Priority",
    //     icon: <PuzzlePieceIcon className="h-4" />,
    //     route: "admin.priority.index",
    //     permission: "REGISTRATION",
    // },
    // {
    //     id: "advance.print",
    //     name: "Advance Print",
    //     icon: <UserPlusIcon className="h-4" />,
    //     route: "admin.advance-print.index",
    //     permission: "REGISTRATION",
    // },

    {
        id: "configurations",
        name: "Configurations",
        icon: <Cog6ToothIcon className="h-4" />,
        route: "admin.configurations.index",
        permission: "CONFIGURATIONS",
    },
    {
        id: "setup",
        name: "Setup",
        icon: <WrenchScrewdriverIcon className="h-4" />,
        route: "admin.setup.*",
        permission: "CONFIGURATIONS",
        children: [
            {
                id: "account.types",
                name: "Departments",
                icon: <CubeIcon className="h-4" />,
                route: "admin.setup.account-types.index",
                permission: "ACCOUNT_TYPES",
            },
            {
                id: "categories",
                name: "Categories",
                icon: <CubeIcon className="h-4" />,
                route: "admin.setup.categories.index",
                permission: "CATEGORIES",
            },
            {
                id: "numformat",
                name: "Formats",
                icon: <SquaresPlusIcon className="h-4" />,
                route: "admin.setup.formats.index",
                permission: "FORMATS",
            },
            {
                id: "screens",
                name: "Screens",
                icon: <SquaresPlusIcon className="h-4" />,
                route: "admin.setup.screen.index",
                permission: "SCREENS",
            },
            {
                id: "shared-series",
                name: "Shared Series",
                icon: <SquaresPlusIcon className="h-4" />,
                route: "admin.setup.shared-series.index",
                permission: "SHARED_SERIES",
            },
        ],
    },
    {
        id: "users",
        name: "Users",
        icon: <UserGroupIcon className="h-4" />,
        route: "admin.users.index",
        permission: "USERS",
    },
    {
        id: "audit",
        name: "Audit Trails",
        icon: <SwatchIcon className="h-4" />,
        route: "admin.audit.index",
        permission: "AUDIT",
    },
];
